[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:juice-shop]
command=node /juice-shop/build/app.js
directory=/juice-shop
environment=NODE_ENV="production"
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:logging-proxy]
; Wait 15s for Juice Shop to start before proxy comes up
command=node /logging-proxy/logging-proxy.js
directory=/logging-proxy
autostart=true
autorestart=true
startsecs=15
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
